from __future__ import annotations

from typing import Any, Protocol

from .schemas import RAGAnswer, RetrievedChunk, TextChunk, Transcript


class SpeechToTextProvider(Protocol):
    def transcribe(self, audio_path: str) -> Transcript:
        """Return a transcript for a local audio file."""


class LLMProvider(Protocol):
    def generate_json(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        response_schema: dict[str, Any] | None = None,
    ) -> dict:
        """Return a JSON-compatible dict generated by a local model."""

    def answer(self, *, system_prompt: str, user_prompt: str) -> RAGAnswer:
        """Return a grounded answer generated by a local model."""


class EmbeddingProvider(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]:
        """Return local embeddings for the input texts."""


class VectorStore(Protocol):
    def upsert(self, chunks: list[TextChunk], vectors: list[list[float]]) -> None:
        """Persist chunks and vectors locally."""

    def search(self, *, patient_id: str, query_vector: list[float], top_k: int) -> list[RetrievedChunk]:
        """Return the most relevant chunks for one patient."""
